# Generated by Django 2.2.2 on 2019-06-03 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareddocuments',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_document', to='api.Document'),
        ),
        migrations.AlterField(
            model_name='shareddocuments',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
