# Generated by Django 2.2.2 on 2019-06-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshortener',
            name='active',
        ),
    ]
